settings:
  APP_DISPLAY_NAME: Munawar X
  PRODUCTION_APP_NAME: Munawar
  APP_GROUP_IDENTIFIER: group.io.element
  BASE_BUNDLE_IDENTIFIER: io.element.elementx
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 7J4U792NQT
